Fix some UB in signal handling
pengutronix/microcom pull request #18
Opened 2019-08-25 19:50 UTC by a3f

While looking over #15, I noticed some issues with the way microcom handles signals. This fixes what was straight forward to fix. What remains is the access to `ios`, `ios->exit` and  whatever is called there. With #15 merged, this could be fixed by peppering some `volatile` around, but it's very unlikely to happen so postponing this for now.

2019-08-25 21:19 UTC, ukleinek submitted a review, later dismissed

2019-08-25 21:20 UTC, ukleinek commented
Sorry, github UI problems. I only intended to approve the first commit.

2019-08-25 21:26 UTC, ukleinek reviewed
Hmm, I don't particularly like this. I'd like to allow backends calling async-unsafe functions. Freeing ios in global code seems to work, but is a layer violation because the structure was allocated in the backends. I'll think about that, if you want to improve this while I think that would be welcome of course :-)

2019-08-25 21:37 UTC, a3f commented
> Hmm, I don't particularly like this. I'd like to allow backends calling async-unsafe functions.

We could `longjmp` back into `main` and exit regularly there. Thinking about it, I like this approach more as well. What do you think?

> Freeing ios in global code seems to work, but is a layer violation because the structure was allocated in the backends.

Is it? `malloc`, `calloc` and `strdup` are all free'd by the same `free`. Same goes for `open`, `socket` and `creat`, which are all destructed by `close`.

2025-06-04 09:26 UTC, jonrebm commented
Could you elaborate on the type of issue this resolves? Do we have reproducible crashes, hypothetical undefined behavior or is this just about following best-practices?
Is the issue still present on current master?

2026-01-14 10:45 UTC, jonrebm requested changes
Hi @a3f 
I just now noticed the overlap this has with https://github.com/pengutronix/microcom/pull/55 and https://github.com/pengutronix/microcom/pull/56 

I would like to apply your pr here first, then rebase mine.

2026-01-14 10:45 UTC, jonrebm commented on commands.c
> +	free(ios);
```suggestion
```
I suppose we can just skip the free when exit is imminent

2026-01-14 10:45 UTC, jonrebm commented on microcom.c
> +		sigemptyset(&sact.sa_mask);
```suggestion
```
Looking at the [example in the sigaction manpage](https://man7.org/linux/man-pages/man2/sigaction.2.html#EXAMPLES), zero initializing `struct sigaction` should suffice

2026-01-15 16:00 UTC, merged