serial: use flock instead of lock files
pengutronix/microcom pull request #28
Opened 2021-05-28 15:14 UTC by lynxeye-dev

Some distributions like Fedora don't allow users access to /var/lock and
instead want applications to use lockdev, which in turn isn't available
in distributions like Debian, as those rightfully state [1] that there is a
much more convenient and and easier to get right interface available in
the form of flock(2).

Switch microcom to use flock instead of the hand rolled lockfiles, which
also avoids the issue of stale lock files, as the lock is automatically
removed when the application closes the serial fd.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734086

2021-06-14 13:03 UTC, a3f requested changes
I did a short test on my Debian 11 host:

- minicom 2.8: uses lock files
- picocom v3.1: use flock

Given that we can expect more tools to gradually use flock, I am in favor of this change.
The commit message should be explicit though, that we will no longer lock against some tools, like minicom.
The commit message and link read as if Debian already embraced the brave new world, but apparently there are still hold outs. (On a related note, can you run strace for minicom and find out what it does on Fedora?)

2021-06-14 13:03 UTC, a3f commented on serial.c
> +		else
Can be dropped. `main_usage` doesn't return.

2022-01-20 15:51 UTC, lynxeye-dev commented on serial.c
> +		else
I don't see what you want dropped here: either we stop execution via main_usage, or print a message and continue depending on the force option.

2022-01-20 15:54 UTC, a3f commented on serial.c
> +		else
The `else` itself can be dropped, not its content. Just a nitpick.

2022-01-21 08:09 UTC, ukleinek commented
Alternative approach: https://github.com/ukleinek/microcom/tree/rework-locking

2022-01-21 09:29 UTC, lynxeye-dev commented
> Alternative approach: https://github.com/ukleinek/microcom/tree/rework-locking

Sorry, but I just don't see the value of keeping the lock file stuff around. Even slow moving Distros like Debian want to get away from this way of locking serial devices (see the linked Debian Bug report). Please let us move microcom to thetechnology of the current millennium and drop the complexity introduced by lockfiles.

2022-02-11 08:07 UTC, merged